-- MySQL Script generated by MySQL Workbench
-- Tue May  7 12:06:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`type_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type_item` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`items` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(1000) NOT NULL,
  `picturepath` VARCHAR(45) NULL,
  `typeitem_id` INT NOT NULL,
  PRIMARY KEY (`id`, `typeitem_id`),
  INDEX `fk_items_typeitem1_idx` (`typeitem_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_typeitem1`
    FOREIGN KEY (`typeitem_id`)
    REFERENCES `mydb`.`type_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`containers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`containers` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`loot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loot` (
  `id` INT NOT NULL,
  `chance` TINYINT NOT NULL,
  `containers_id` INT NOT NULL,
  `items_id` INT NOT NULL,
  PRIMARY KEY (`id`, `containers_id`, `items_id`),
  INDEX `fk_loot_containers_idx` (`containers_id` ASC) VISIBLE,
  INDEX `fk_loot_items1_idx` (`items_id` ASC) VISIBLE,
  CONSTRAINT `fk_loot_containers`
    FOREIGN KEY (`containers_id`)
    REFERENCES `mydb`.`containers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loot_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `mydb`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`countries` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ship_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ship_class` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ships` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  `level` INT NULL,
  `survivability` INT NULL,
  `aircraft` INT NULL,
  `artillery` INT NULL,
  `torpedoes` INT NULL,
  `airdefense` INT NULL,
  `maneuverability` INT NULL,
  `concealment` INT NULL,
  `pricemoney` INT NULL,
  `priceexp` INT NULL,
  `countries_id` INT NOT NULL,
  `shipclass_id` INT NOT NULL,
  PRIMARY KEY (`id`, `countries_id`, `shipclass_id`),
  INDEX `fk_ships_country1_idx` (`countries_id` ASC) VISIBLE,
  INDEX `fk_ships_shipclass1_idx` (`shipclass_id` ASC) VISIBLE,
  CONSTRAINT `fk_ships_country1`
    FOREIGN KEY (`countries_id`)
    REFERENCES `mydb`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ships_shipclass1`
    FOREIGN KEY (`shipclass_id`)
    REFERENCES `mydb`.`ship_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recommended_signals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recommended_signals` (
  `id` INT NOT NULL,
  `raiting` INT NOT NULL,
  `items_id` INT NOT NULL,
  `ships_id` INT NOT NULL,
  PRIMARY KEY (`id`, `items_id`, `ships_id`),
  INDEX `fk_recommendedsignals_items1_idx` (`items_id` ASC) VISIBLE,
  INDEX `fk_recommendedsignals_ships1_idx` (`ships_id` ASC) VISIBLE,
  CONSTRAINT `fk_recommendedsignals_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `mydb`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recommendedsignals_ships1`
    FOREIGN KEY (`ships_id`)
    REFERENCES `mydb`.`ships` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consumables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consumables` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `actiontime` VARCHAR(5) NULL,
  `cooldown` VARCHAR(5) NULL,
  `charges` VARCHAR(5) NULL,
  `picturepath` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consumables_has_ships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consumables_has_ships` (
  `consumables_id` INT NOT NULL,
  `ships_id` INT NOT NULL,
  PRIMARY KEY (`consumables_id`, `ships_id`),
  INDEX `fk_consumables_has_ships_ships1_idx` (`ships_id` ASC) VISIBLE,
  INDEX `fk_consumables_has_ships_consumables1_idx` (`consumables_id` ASC) VISIBLE,
  CONSTRAINT `fk_consumables_has_ships_consumables1`
    FOREIGN KEY (`consumables_id`)
    REFERENCES `mydb`.`consumables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumables_has_ships_ships1`
    FOREIGN KEY (`ships_id`)
    REFERENCES `mydb`.`ships` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type_achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type_achievements` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`achievements` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  `typeachivements_id` INT NOT NULL,
  PRIMARY KEY (`id`, `typeachivements_id`),
  INDEX `fk_achievements_typeachivements1_idx` (`typeachivements_id` ASC) VISIBLE,
  CONSTRAINT `fk_achievements_typeachivements1`
    FOREIGN KEY (`typeachivements_id`)
    REFERENCES `mydb`.`type_achievements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maps` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  `battletiers` VARCHAR(45) NULL,
  `size` VARCHAR(45) NULL,
  `replyfilename` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player_levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player_levels` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  `battleneed` TINYINT NULL,
  `battletotal` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modules` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  `pricemoney` INT NULL,
  `priceexp` INT NULL,
  `ships_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ships_id`),
  INDEX `fk_modules_ships1_idx` (`ships_id` ASC) VISIBLE,
  CONSTRAINT `fk_modules_ships1`
    FOREIGN KEY (`ships_id`)
    REFERENCES `mydb`.`ships` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`effect_name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`effect_name` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`effect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`effect` (
  `id` INT NOT NULL,
  `value` TINYINT NOT NULL,
  `consumables_id` INT NOT NULL,
  `effectname_id` INT NOT NULL,
  PRIMARY KEY (`id`, `consumables_id`, `effectname_id`),
  INDEX `fk_effect_consumables1_idx` (`consumables_id` ASC) VISIBLE,
  INDEX `fk_effect_effectname1_idx` (`effectname_id` ASC) VISIBLE,
  CONSTRAINT `fk_effect_consumables1`
    FOREIGN KEY (`consumables_id`)
    REFERENCES `mydb`.`consumables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_effect_effectname1`
    FOREIGN KEY (`effectname_id`)
    REFERENCES `mydb`.`effect_name` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`upgrades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`upgrades` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `discription` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  `slot` TINYINT(1) NULL,
  `pricemoney` INT NULL,
  `effect_id` INT NOT NULL,
  `effect_consumables_id` INT NOT NULL,
  `effect_effectname_id` INT NOT NULL,
  PRIMARY KEY (`id`, `effect_id`, `effect_consumables_id`, `effect_effectname_id`),
  INDEX `fk_upgrades_effect1_idx` (`effect_id` ASC, `effect_consumables_id` ASC, `effect_effectname_id` ASC) VISIBLE,
  CONSTRAINT `fk_upgrades_effect1`
    FOREIGN KEY (`effect_id` , `effect_consumables_id` , `effect_effectname_id`)
    REFERENCES `mydb`.`effect` (`id` , `consumables_id` , `effectname_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ships_has_upgrades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ships_has_upgrades` (
  `ships_id` INT NOT NULL,
  `ships_modules_id` INT NOT NULL,
  `ships_modules_type_of_price_id` INT NOT NULL,
  `upgrades_id` INT NOT NULL,
  PRIMARY KEY (`ships_id`, `ships_modules_id`, `ships_modules_type_of_price_id`, `upgrades_id`),
  INDEX `fk_ships_has_upgrades_upgrades1_idx` (`upgrades_id` ASC) VISIBLE,
  INDEX `fk_ships_has_upgrades_ships1_idx` (`ships_id` ASC, `ships_modules_id` ASC, `ships_modules_type_of_price_id` ASC) VISIBLE,
  CONSTRAINT `fk_ships_has_upgrades_ships1`
    FOREIGN KEY (`ships_id`)
    REFERENCES `mydb`.`ships` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ships_has_upgrades_upgrades1`
    FOREIGN KEY (`upgrades_id`)
    REFERENCES `mydb`.`upgrades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`special_commanders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`special_commanders` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  `origins` VARCHAR(100) NULL,
  `countries_id` INT NOT NULL,
  PRIMARY KEY (`id`, `countries_id`),
  INDEX `fk_specialcommanders_country1_idx` (`countries_id` ASC) VISIBLE,
  CONSTRAINT `fk_specialcommanders_country1`
    FOREIGN KEY (`countries_id`)
    REFERENCES `mydb`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`base_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base_skills` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  `priceskillpoints` TINYINT(1) NULL,
  `effect_id` INT NOT NULL,
  `effect_consumables_id` INT NOT NULL,
  `effect_effectname_id` INT NOT NULL,
  PRIMARY KEY (`id`, `effect_id`, `effect_consumables_id`, `effect_effectname_id`),
  INDEX `fk_baseskills_effect1_idx` (`effect_id` ASC, `effect_consumables_id` ASC, `effect_effectname_id` ASC) VISIBLE,
  CONSTRAINT `fk_baseskills_effect1`
    FOREIGN KEY (`effect_id` , `effect_consumables_id` , `effect_effectname_id`)
    REFERENCES `mydb`.`effect` (`id` , `consumables_id` , `effectname_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shipclass_has_baseskills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shipclass_has_baseskills` (
  `shipclass_id` INT NOT NULL,
  `baseskills_id` INT NOT NULL,
  PRIMARY KEY (`shipclass_id`, `baseskills_id`),
  INDEX `fk_shipclass_has_baseskills_baseskills1_idx` (`baseskills_id` ASC) VISIBLE,
  INDEX `fk_shipclass_has_baseskills_shipclass1_idx` (`shipclass_id` ASC) VISIBLE,
  CONSTRAINT `fk_shipclass_has_baseskills_shipclass1`
    FOREIGN KEY (`shipclass_id`)
    REFERENCES `mydb`.`ship_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipclass_has_baseskills_baseskills1`
    FOREIGN KEY (`baseskills_id`)
    REFERENCES `mydb`.`base_skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enhenced_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enhenced_skills` (
  `id` INT NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `baseskills_id` INT NOT NULL,
  `baseskills_effect_id` INT NOT NULL,
  `baseskills_effect_consumables_id` INT NOT NULL,
  `baseskills_effect_effectname_id` INT NOT NULL,
  PRIMARY KEY (`id`, `baseskills_id`, `baseskills_effect_id`, `baseskills_effect_consumables_id`, `baseskills_effect_effectname_id`),
  INDEX `fk_enhencedskills_baseskills1_idx` (`baseskills_id` ASC, `baseskills_effect_id` ASC, `baseskills_effect_consumables_id` ASC, `baseskills_effect_effectname_id` ASC) VISIBLE,
  CONSTRAINT `fk_enhencedskills_baseskills1`
    FOREIGN KEY (`baseskills_id` , `baseskills_effect_id` , `baseskills_effect_consumables_id` , `baseskills_effect_effectname_id`)
    REFERENCES `mydb`.`base_skills` (`id` , `effect_id` , `effect_consumables_id` , `effect_effectname_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`talents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`talents` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `picturepath` VARCHAR(45) NULL,
  `specialcommanders_id` INT NOT NULL,
  PRIMARY KEY (`id`, `specialcommanders_id`),
  INDEX `fk_talents_specialcommanders1_idx` (`specialcommanders_id` ASC) VISIBLE,
  CONSTRAINT `fk_talents_specialcommanders1`
    FOREIGN KEY (`specialcommanders_id`)
    REFERENCES `mydb`.`special_commanders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enhencedskills_has_specialcommanders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enhencedskills_has_specialcommanders` (
  `enhencedskills_id` INT NOT NULL,
  `specialcommanders_id` INT NOT NULL,
  PRIMARY KEY (`enhencedskills_id`, `specialcommanders_id`),
  INDEX `fk_enhencedskills_has_specialcommanders_specialcommanders1_idx` (`specialcommanders_id` ASC) VISIBLE,
  INDEX `fk_enhencedskills_has_specialcommanders_enhencedskills1_idx` (`enhencedskills_id` ASC) VISIBLE,
  CONSTRAINT `fk_enhencedskills_has_specialcommanders_enhencedskills1`
    FOREIGN KEY (`enhencedskills_id`)
    REFERENCES `mydb`.`enhenced_skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enhencedskills_has_specialcommanders_specialcommanders1`
    FOREIGN KEY (`specialcommanders_id`)
    REFERENCES `mydb`.`special_commanders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
